# Generated by Django 5.0.1 on 2024-06-08 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('IDHerramienta', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'Herramienta',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('IDItem', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.PositiveIntegerField(default=1)),
                ('Descripcion', models.TextField(max_length=200)),
                ('PrecioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PrecioTotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('IDMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('IDProforma', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.PositiveIntegerField()),
                ('Solicitante', models.TextField(max_length=50, null=True)),
                ('Lugar', models.TextField(max_length=50, null=True)),
                ('Tiempo', models.PositiveSmallIntegerField(null=True)),
                ('FechaCreacion', models.DateField()),
                ('Estado', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'Proforma',
            },
        ),
        migrations.CreateModel(
            name='ProformaHerramienta',
            fields=[
                ('IDProformaMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('IDHerramienta', models.ForeignKey(db_column='IDHerramienta', on_delete=django.db.models.deletion.CASCADE, to='Proforma.herramienta')),
                ('IDProforma', models.ForeignKey(db_column='IDProforma', on_delete=django.db.models.deletion.CASCADE, to='Proforma.proforma')),
            ],
            options={
                'db_table': 'ProformaHerramienta',
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('IDProformaItem', models.AutoField(primary_key=True, serialize=False)),
                ('IDItem', models.ForeignKey(db_column='IDItem', on_delete=django.db.models.deletion.CASCADE, to='Proforma.item')),
                ('IDProforma', models.ForeignKey(db_column='IDProforma', on_delete=django.db.models.deletion.CASCADE, to='Proforma.proforma')),
            ],
            options={
                'db_table': 'ProformaItem',
            },
        ),
        migrations.CreateModel(
            name='ProformaMaterial',
            fields=[
                ('IDProformaMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('IDMaterial', models.ForeignKey(db_column='IDMaterial', on_delete=django.db.models.deletion.CASCADE, to='Proforma.material')),
                ('IDProforma', models.ForeignKey(db_column='IDProforma', on_delete=django.db.models.deletion.CASCADE, to='Proforma.proforma')),
            ],
            options={
                'db_table': 'ProformaMaterial',
            },
        ),
    ]
