# Generated by Django 5.0.1 on 2024-06-09 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_empresa_nombre'),
        ('Proforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='IDEmpresa',
            field=models.ForeignKey(db_column='IDEmpresa', default=1, on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa'),
            preserve_default=False,
        ),
    ]
