# Generated by Django 5.0.1 on 2024-06-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='Nombre',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
