# Generated by Django 5.0.1 on 2024-06-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_empresa_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='Ruc',
            field=models.TextField(max_length=11, null=True),
        ),
    ]
